# TPOT AUTOML

In [15]:
from tpot import TPOTRegressor
import pandas as pd
from pandas import read_excel
from sklearn.model_selection import train_test_split

In [16]:

filename='Real_Combine.csv'
df=pd.read_csv(filename,header=0)
df.head(5)

T    TM   Tm     SLP     H   VV    V    VM      PM 2.5
0   7.4   9.8  4.8  1017.6  93.0  0.5  4.3   9.4  219.720833
1   7.8  12.7  4.4  1018.5  87.0  0.6  4.4  11.1  182.187500
2   6.7  13.4  2.4  1019.4  82.0  0.6  4.8  11.1  154.037500
3   8.6  15.5  3.3  1018.7  72.0  0.8  8.1  20.6  223.208333
4  12.4  20.9  4.4  1017.3  61.0  1.3  8.7  22.2  200.645833

In [17]:
'''
import tkinter as tk
from tkinter import filedialog
import pandas as pd

root= tk.Tk()

canvas1 = tk.Canvas(root, width = 300, height = 300, bg = 'lightsteelblue')
canvas1.pack()

def getExcel ():
    global df
    
    import_file_path = filedialog.askopenfilename()
    df = pd.read_excel (import_file_path)
    print (df)
    
browseButton_Excel = tk.Button(text='Import Excel File', command=getExcel, bg='green', fg='white', font=('helvetica', 12, 'bold'))
canvas1.create_window(150, 150, window=browseButton_Excel)

root.mainloop()
'''

"\nimport tkinter as tk\nfrom tkinter import filedialog\nimport pandas as pd\n\nroot= tk.Tk()\n\ncanvas1 = tk.Canvas(root, width = 300, height = 300, bg = 'lightsteelblue')\ncanvas1.pack()\n\ndef getExcel ():\n    global df\n    \n    import_file_path = filedialog.askopenfilename()\n    df = pd.read_excel (import_file_path)\n    print (df)\n    \nbrowseButton_Excel = tk.Button(text='Import Excel File', command=getExcel, bg='green', fg='white', font=('helvetica', 12, 'bold'))\ncanvas1.create_window(150, 150, window=browseButton_Excel)\n\nroot.mainloop()\n"

In [18]:
df.head(5)

T    TM   Tm     SLP     H   VV    V    VM      PM 2.5
0   7.4   9.8  4.8  1017.6  93.0  0.5  4.3   9.4  219.720833
1   7.8  12.7  4.4  1018.5  87.0  0.6  4.4  11.1  182.187500
2   6.7  13.4  2.4  1019.4  82.0  0.6  4.8  11.1  154.037500
3   8.6  15.5  3.3  1018.7  72.0  0.8  8.1  20.6  223.208333
4  12.4  20.9  4.4  1017.3  61.0  1.3  8.7  22.2  200.645833

In [22]:
dftarget=df['PM 2.5']

In [23]:
df=df.dropna()
X=df.iloc[:,:-1] ## independent features
y=df.iloc[:,-1] ## dependent features

In [24]:
## check null values
X.isnull()

T     TM     Tm    SLP      H     VV      V     VM
0     False  False  False  False  False  False  False  False
1     False  False  False  False  False  False  False  False
2     False  False  False  False  False  False  False  False
3     False  False  False  False  False  False  False  False
4     False  False  False  False  False  False  False  False
5     False  False  False  False  False  False  False  False
6     False  False  False  False  False  False  False  False
7     False  False  False  False  False  False  False  False
8     False  False  False  False  False  False  False  False
9     False  False  False  False  False  False  False  False
10    False  False  False  False  False  False  False  False
11    False  False  False  False  False  False  False  False
12    False  False  False  False  False  False  False  False
13    False  False  False  False  False  False  False  False
14    False  False  False  False  False  False  False  False
15    False  False  False  False  False  False  False  False
16    False  False  False  False  False  False  False  False
17    False  False  False  False  False  False  False  False
18    False  False  False  False  False  False  False  False
19    False  False  False  False  False  False  False  False
20    False  False  False  False  False  False  False  False
21    False  False  False  False  False  False  False  False
22    False  False  False  False  False  False  False  False
23    False  False  False  False  False  False  False  False
24    False  False  False  False  False  False  False  False
25    False  False  False  False  False  False  False  False
26    False  False  False  False  False  False  False  False
27    False  False  False  False  False  False  False  False
28    False  False  False  False  False  False  False  False
29    False  False  False  False  False  False  False  False
...     ...    ...    ...    ...    ...    ...    ...    ...
1059  False  False  False  False  False  False  False  False
1060  False  False  False  False  False  False  False  False
1061  False  False  False  False  False  False  False  False
1062  False  False  False  False  False  False  False  False
1063  False  False  False  False  False  False  False  False
1064  False  False  False  False  False  False  False  False
1065  False  False  False  False  False  False  False  False
1066  False  False  False  False  False  False  False  False
1067  False  False  False  False  False  False  False  False
1068  False  False  False  False  False  False  False  False
1069  False  False  False  False  False  False  False  False
1070  False  False  False  False  False  False  False  False
1071  False  False  False  False  False  False  False  False
1072  False  False  False  False  False  False  False  False
1073  False  False  False  False  False  False  False  False
1074  False  False  False  False  False  False  False  False
1075  False  False  False  False  False  False  False  False
1076  False  False  False  False  False  False  False  False
1077  False  False  False  False  False  False  False  False
1078  False  False  False  False  False  False  False  False
1079  False  False  False  False  False  False  False  False
1080  False  False  False  False  False  False  False  False
1081  False  False  False  False  False  False  False  False
1082  False  False  False  False  False  False  False  False
1083  False  False  False  False  False  False  False  False
1084  False  False  False  False  False  False  False  False
1085  False  False  False  False  False  False  False  False
1086  False  False  False  False  False  False  False  False
1087  False  False  False  False  False  False  False  False
1088  False  False  False  False  False  False  False  False

[1088 rows x 8 columns]

In [25]:
type(df)
df



T    TM    Tm     SLP     H   VV     V    VM      PM 2.5
0      7.4   9.8   4.8  1017.6  93.0  0.5   4.3   9.4  219.720833
1      7.8  12.7   4.4  1018.5  87.0  0.6   4.4  11.1  182.187500
2      6.7  13.4   2.4  1019.4  82.0  0.6   4.8  11.1  154.037500
3      8.6  15.5   3.3  1018.7  72.0  0.8   8.1  20.6  223.208333
4     12.4  20.9   4.4  1017.3  61.0  1.3   8.7  22.2  200.645833
5     16.0  25.2  10.0  1013.2  79.0  0.6   4.8  11.1  285.225000
6     13.4  21.0   9.2  1015.1  87.0  0.5   1.5   7.6  236.825000
7     14.3  22.6   6.6  1016.3  76.0  0.8   0.4   3.5  276.908333
8     12.7  18.9   7.3  1021.2  76.0  1.8   6.1  16.5  108.000000
9     11.9  18.9   6.3  1020.1  76.0  1.1   8.3  20.6  107.625000
10    12.2  19.9   6.2  1021.0  69.0  2.1   4.4  18.3  125.891667
11    13.4  21.1   5.6  1020.0  60.0  1.9   8.0  22.2  181.012500
12    12.3  21.4   6.4  1019.6  70.0  1.9   6.7  14.8  152.554167
13    13.7  22.0   7.0  1018.2  63.0  1.8   7.2  18.3  152.320833
14    14.9  21.9   7.1  1018.3  73.0  0.6   2.0   7.6  319.737500
15    15.0  24.0   7.6  1017.4  81.0  0.6   2.2   7.6  332.708333
16    16.3  24.0  12.0  1017.2  80.0  0.8   1.3   9.4  279.600000
17    18.7  26.3   9.5  1015.3  64.0  1.6   1.7   7.6  179.116667
18    14.6  21.6   9.4  1018.4  72.0  2.7   9.4  18.3   54.791667
19    14.7  21.7   8.4  1017.1  71.0  1.8  10.9  22.2   93.375000
20    14.8  22.6   8.5  1016.8  67.0  2.1   9.3  18.3  103.000000
21    17.4  25.4  10.3  1015.8  63.0  1.9   6.7  14.8  132.208333
22    18.1  26.7  10.2  1013.8  61.0  2.6   5.0  11.1  127.708333
23    18.3  23.2  12.7  1011.2  75.0  1.9  10.0  22.2  109.333333
24    16.4  22.0  11.2  1015.5  81.0  1.6   5.9  18.3   56.458333
25    16.9  23.5  10.1  1016.8  80.0  1.3   5.2  22.2  135.833333
26    19.3  26.9  12.1  1015.6  74.0  1.6   5.9  11.1  122.500000
27    17.2  24.2  10.8  1018.3  74.0  2.6   4.6  14.8   69.666667
28    17.7  26.5   9.8  1015.3  73.0  1.4   4.8  14.8   79.833333
29    20.4  28.4  15.2  1014.7  62.0  2.4   5.0  14.8   62.708333
...    ...   ...   ...     ...   ...  ...   ...   ...         ...
1059  27.1  34.0  17.8  1011.0  54.0  2.3   2.8   9.4  156.250000
1060  26.0  33.8  17.4  1013.8  52.0  2.4   2.0   7.6  156.000000
1061  24.5  32.5  15.0  1014.8  58.0  2.4   2.0   7.6  252.625000
1062  24.2  32.4  15.8  1016.8  59.0  2.1   0.6   5.4  119.416667
1063  24.2  31.0  15.6  1016.7  62.0  1.9   2.4   9.4  126.000000
1064  24.1  31.0  16.0  1015.3  63.0  1.6   2.2  10.7  232.333333
1065  24.1  31.1  16.0  1014.3  65.0  1.6   5.0  14.4  215.541667
1066  24.6  32.0  16.0  1012.1  63.0  1.6   4.1   7.6  239.416667
1067  25.2  31.6  18.5  1011.7  63.0  1.9   9.4  14.8  196.541667
1068  20.3  28.0  12.5  1015.7  44.0  3.1   8.3  18.3  232.541667
1069  18.6  27.8  10.5  1014.7  58.0  1.4   1.1   3.5  185.500000
1070  21.9  30.2  14.2  1009.6  74.0  1.3   4.1   9.4  257.666667
1071  22.2  29.4  17.6  1011.4  77.0  2.3   5.4  14.8  166.875000
1072  22.2  28.5  16.2  1015.2  67.0  2.4   4.8   9.4  135.166667
1073  19.3  27.9  10.4  1016.4  59.0  2.9   2.0   9.4  135.583333
1074  19.8  27.2  10.5  1016.3  64.0  2.1   0.7   5.4  152.041667
1075  20.8  28.2  10.7  1018.0  65.0  1.9   0.9   5.4  141.416667
1076  19.6  28.0   9.0  1014.6  56.0  2.4   2.4  11.1   91.750000
1077  18.9  28.1   8.6  1016.7  58.0  1.9   3.5   9.4   99.916667
1078  17.5  25.1   8.8  1015.7  67.0  1.9   4.8  22.2  119.708333
1079  16.5  24.2   7.6  1016.3  70.0  1.8   2.8  11.1  110.875000
1080  17.4  25.0   8.2  1014.9  66.0  1.8   1.1   7.6  200.333333
1081  15.7  21.4   8.0  1022.8  74.0  1.9   5.9  14.8   25.083333
1082  15.3  22.0   8.2  1022.3  78.0  1.9   5.6  13.0   57.083333
1083  14.8  22.3   5.2  1018.9  67.0  2.1   4.6  11.1  349.291667
1084  12.3  22.4   4.0  1017.9  74.0  1.3   1.1   3.5  188.041667
1085  11.3  22.3   4.7  1017.7  82.0  1.1   3.0   3.5  310.250000
1086  12.3  19.4   6.2  1016.8  80.0  1.3   6.7  25.9  204.375000
1087  11.1  20.6   3.6  1015.7  76.0  1.3   3.0  

In [26]:
y.isnull()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...  
1059    False
1060    False
1061    False
1062    False
1063    False
1064    False
1065    False
1066    False
1067    False
1068    False
1069    False
1070    False
1071    False
1072    False
1073    False
1074    False
1075    False
1076    False
1077    False
1078    False
1079    False
1080    False
1081    False
1082    False
1083    False
1084    False
1085    False
1086    False
1087    False
1088    False
Name: PM 2.5, Length: 1088, dtype: bool

In [27]:
df=df.drop(columns=['PM 2.5'])

In [31]:
df.head(5),dftarget.head(5)

(      T    TM   Tm     SLP     H   VV    V    VM
 0   7.4   9.8  4.8  1017.6  93.0  0.5  4.3   9.4
 1   7.8  12.7  4.4  1018.5  87.0  0.6  4.4  11.1
 2   6.7  13.4  2.4  1019.4  82.0  0.6  4.8  11.1
 3   8.6  15.5  3.3  1018.7  72.0  0.8  8.1  20.6
 4  12.4  20.9  4.4  1017.3  61.0  1.3  8.7  22.2, 0    219.720833
 1    182.187500
 2    154.037500
 3    223.208333
 4    200.645833
 Name: PM 2.5, dtype: float64)

In [32]:
dfnp=df.to_numpy()
dftargetnp=dftarget.to_numpy()

In [33]:
dfnp[:,:],dftargetnp

(array([[ 7.4,  9.8,  4.8, ...,  0.5,  4.3,  9.4],
        [ 7.8, 12.7,  4.4, ...,  0.6,  4.4, 11.1],
        [ 6.7, 13.4,  2.4, ...,  0.6,  4.8, 11.1],
        ...,
        [12.3, 19.4,  6.2, ...,  1.3,  6.7, 25.9],
        [11.1, 20.6,  3.6, ...,  1.3,  3. ,  9.4],
        [11.6, 21.4,  3.4, ...,  1.1,  2.4,  5.4]]),
 array([219.72083333, 182.1875    , 154.0375    , ..., 204.375     ,
        223.25      , 248.95833333]))

In [34]:
type(dfnp),type(dftargetnp)

(numpy.ndarray, numpy.ndarray)

In [35]:
type(df),type(dftarget)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [36]:

X_train, X_test, y_train, y_test = train_test_split(dfnp, dftargetnp,
                                                    train_size=0.75, test_size=0.25)
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((816, 8), (272, 8), (816,), (272,))

In [53]:
from sklearn.preprocessing import MinMaxScaler
sc_X = MinMaxScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [54]:
X_test

array([[0.90064103, 0.92436975, 0.70570571, ..., 0.54054054, 0.38333333,
        0.29443447],
       [0.20833333, 0.30812325, 0.17117117, ..., 0.2972973 , 0.3375    ,
        0.23159785],
       [0.33653846, 0.41456583, 0.24924925, ..., 0.2972973 , 0.35416667,
        0.23159785],
       ...,
       [0.81410256, 0.81792717, 0.6996997 , ..., 0.75675676, 0.22916667,
        0.33572711],
       [0.80769231, 0.8627451 , 0.78078078, ..., 0.43243243, 0.54583333,
        0.33572711],
       [0.32692308, 0.43977591, 0.29429429, ..., 0.54054054, 0.21666667,
        0.36445242]])

In [55]:
X_train

array([[0.77564103, 0.70588235, 0.80780781, ..., 0.43243243, 0.22916667,
        0.23159785],
       [0.39102564, 0.51260504, 0.23723724, ..., 0.43243243, 0.12916667,
        0.13464991],
       [0.38141026, 0.49019608, 0.35435435, ..., 0.62162162, 0.14583333,
        0.19928187],
       ...,
       [0.77564103, 0.71988796, 0.81081081, ..., 0.43243243, 0.59166667,
        0.46499102],
       [0.58333333, 0.61344538, 0.45345345, ..., 0.62162162, 0.22916667,
        0.19928187],
       [0.64102564, 0.52941176, 0.73573574, ..., 0.43243243, 0.1125    ,
        0.19928187]])

In [61]:
tpot = TPOTRegressor(verbosity=2, max_time_mins=10)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

Generation 1 - Current best internal CV score: -2640.9027375858
Generation 2 - Current best internal CV score: -2640.9027375858
Generation 3 - Current best internal CV score: -2620.5544752808864
Generation 4 - Current best internal CV score: -2581.334620346249
Generation 5 - Current best internal CV score: -2577.5640312622163

10.968137983333333 minutes have elapsed. TPOT will close down.
TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: ExtraTreesRegressor(PCA(input_matrix, iterated_power=7, svd_solver=randomized), bootstrap=False, max_features=1.0, min_samples_leaf=1, min_samples_split=9, n_estimators=100)
-2691.2502967273895


In [67]:
tpot.fitted_pipeline_

Pipeline(memory=None,
     steps=[('pca', PCA(copy=True, iterated_power=7, n_components=None, random_state=None,
  svd_solver='randomized', tol=0.0, whiten=False)), ('extratreesregressor', ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features=1.0, max_leaf_nodes=None, min_impurity_decrea...ators=100, n_jobs=None,
          oob_score=False, random_state=None, verbose=0, warm_start=False))])

In [65]:
print(tpot.score(X_test, y_test))

-2691.2502967273895
